### ISSUE TITLE
Need help_Could you update the Java version of Demo code?

### ISSUE THREAD

**Issue by sav7ng** [wzul/Billplz-API-Java#1]
Could you update the Java version of Demo code?

**Comment by sav7ng** [comment]
The company has encountered difficulties in connecting with Billplz's payment interface. I hope to give a Java version of the code Demo,Trouble.

**Comment by sav7ng** [comment]
Because this code is two years ago, it seems that it is not compatible with the current interface

**Comment by sav7ng** [comment]
@nazroof @ganya @arzumy @cherwei

**Comment by wzul** [comment]
Hi.

Please do ignore this repository as it no longer maintained. 

Thanks.
